# Generated by Django 3.1.7 on 2021-04-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbaz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='output_img',
            field=models.ImageField(blank=True, upload_to='out'),
        ),
        migrations.AlterField(
            model_name='image',
            name='input_img',
            field=models.ImageField(blank=True, upload_to='inp'),
        ),
    ]
