# Generated by Django 3.1.7 on 2021-04-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbaz', '0002_auto_20210410_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='input_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='output_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
