# Generated by Django 3.1.7 on 2021-04-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbaz', '0003_auto_20210410_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AlterField(
            model_name='image',
            name='input_img',
            field=models.ImageField(blank=True, upload_to='inp'),
        ),
        migrations.AlterField(
            model_name='image',
            name='output_img',
            field=models.ImageField(blank=True, upload_to='out'),
        ),
    ]
