# Generated by Django 3.1.7 on 2021-04-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbaz', '0005_auto_20210410_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='input_img',
        ),
        migrations.RemoveField(
            model_name='image',
            name='output_img',
        ),
        migrations.AddField(
            model_name='image',
            name='input_loc',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='output_loc',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
